# Generated by Django 4.0.5 on 2022-07-01 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
