# Generated by Django 4.0.5 on 2022-06-30 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealproject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RECIPE_NM', models.CharField(max_length=20)),
                ('QNT', models.CharField(max_length=10)),
                ('RECIPE', models.CharField(max_length=2000)),
            ],
        ),
    ]
