# Generated by Django 4.0.5 on 2022-07-01 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealproject', '0002_recipetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=200)),
                ('unit', models.CharField(max_length=100)),
                ('unitprice', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='MyBoard',
        ),
    ]
