# Generated by Django 4.0.5 on 2022-07-01 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mealproject', '0003_ingredientprice_delete_myboard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IngredientPrice',
        ),
        migrations.DeleteModel(
            name='RecipeTable',
        ),
    ]
