# Generated by Django 4.0.5 on 2022-07-04 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addr', models.CharField(blank=True, max_length=255, null=True)),
                ('storename', models.CharField(blank=True, max_length=255, null=True)),
                ('storetype', models.CharField(blank=True, max_length=255, null=True)),
                ('callnum', models.CharField(blank=True, max_length=255, null=True)),
                ('menu1', models.CharField(blank=True, max_length=255, null=True)),
                ('menu2', models.CharField(blank=True, max_length=255, null=True)),
                ('menu3', models.CharField(blank=True, max_length=255, null=True)),
                ('menu1_price', models.IntegerField(blank=True, null=True)),
                ('menu2_price', models.IntegerField(blank=True, null=True)),
                ('menu3_price', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Map_store',
                'managed': False,
            },
        ),
    ]
